name: ğŸš€ Firebase Distribution

on:
  push:
    branches:
      - main   # ÙŠØ´ØªØºÙ„ Ù„Ù…Ø§ ØªØ¨ÙˆØ´ Ø¹Ù„Ù‰ main ÙÙ‚Ø·

jobs:
  build:
    name: Build & Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2ï¸âƒ£ Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"

      # 3ï¸âƒ£ Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .packages
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 4ï¸âƒ£ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5ï¸âƒ£ Build release APK (faster)
      - name: Build release APK
        run: flutter build apk --release --no-shrink

      # 6ï¸âƒ£ Upload to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:267243080219:android:2bb37f2d1b209523c346be
          token: ${{ secrets.FIREBASE_TOKEN }}
          testers: "badrtest66@gmail.com"
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "ğŸ”¥ Auto build from main branch"
